export const LOGIN_TOKEN = 'token'
export const CACHE_PREFIX = 'EKINGIN_'
export const API_DICT_CATEGORY = '/category/all'
export const API_DICT_ROLE = '/role/all'
export const API_DICT_DEPARTMENT = '/department/all'
